criaturas = [
    {"name": "Ceto", "defeated_by": None, "captured_by": None, "description": None},
    {"name": "Tifón", "defeated_by": "Zeus", "captured_by": None, "description": None},
    {
        "name": "Equidna",
        "defeated_by": "Argos Panoptes",
        "captured_by": None,
        "description": None,
    },
    {"name": "Dino", "defeated_by": None, "captured_by": None, "description": None},
    {"name": "Pefredo", "defeated_by": None, "captured_by": None, "description": None},
    {"name": "Enio", "defeated_by": None, "captured_by": None, "description": None},
    {"name": "Escila", "defeated_by": None, "captured_by": None, "description": None},
    {"name": "Caribdis", "defeated_by": None, "captured_by": None, "description": None},
    {"name": "Euríale", "defeated_by": None, "captured_by": None, "description": None},
    {"name": "Esteno", "defeated_by": None, "captured_by": None, "description": None},
    {
        "name": "Medusa",
        "defeated_by": "Perseo",
        "captured_by": None,
        "description": None,
    },
    {
        "name": "Ladón",
        "defeated_by": "Heracles",
        "captured_by": None,
        "description": None,
    },
    {
        "name": "Águila del Cáucaso",
        "defeated_by": None,
        "captured_by": None,
        "description": None,
    },
    {
        "name": "Quimera",
        "defeated_by": "Belerofonte",
        "captured_by": None,
        "description": None,
    },
    {
        "name": "Hidra de Lerna",
        "defeated_by": "Heracles",
        "captured_by": None,
        "description": None,
    },
    {
        "name": "León de Nemea",
        "defeated_by": "Heracles",
        "captured_by": None,
        "description": None,
    },
    {
        "name": "Esfinge",
        "defeated_by": "Edipo",
        "captured_by": None,
        "description": None,
    },
    {
        "name": "Dragón de la Cólquida",
        "defeated_by": None,
        "captured_by": None,
        "description": None,
    },
    {"name": "Cerbero", "defeated_by": None, "captured_by": None, "description": None},
    {
        "name": "Cerda de Cromión",
        "defeated_by": "Teseo",
        "captured_by": None,
        "description": None,
    },
    {
        "name": "Ortro",
        "defeated_by": "Heracles",
        "captured_by": None,
        "description": None,
    },
    {
        "name": "Toro de Creta",
        "defeated_by": "Teseo",
        "captured_by": None,
        "description": None,
    },
    {
        "name": "Jabalí de Calidón",
        "defeated_by": "Atalanta",
        "captured_by": None,
        "description": None,
    },
    {"name": "Carcinos", "defeated_by": None, "captured_by": None, "description": None},
    {
        "name": "Gerión",
        "defeated_by": "Heracles",
        "captured_by": None,
        "description": None,
    },
    {"name": "Cloto", "defeated_by": None, "captured_by": None, "description": None},
    {"name": "Láquesis", "defeated_by": None, "captured_by": None, "description": None},
    {"name": "Átropos", "defeated_by": None, "captured_by": None, "description": None},
    {
        "name": "Minotauro de Creta",
        "defeated_by": "Teseo",
        "captured_by": None,
        "description": None,
    },
    {"name": "Harpías", "defeated_by": None, "captured_by": None, "description": None},
    {
        "name": "Argos Panoptes",
        "defeated_by": "Hermes",
        "captured_by": None,
        "description": None,
    },
    {
        "name": "Aves del Estínfalo",
        "defeated_by": None,
        "captured_by": None,
        "description": None,
    },
    {"name": "Talos", "defeated_by": "Medea", "captured_by": None, "description": None},
    {"name": "Sirenas", "defeated_by": None, "captured_by": None, "description": None},
    {"name": "Pitón", "defeated_by": "Apolo", "captured_by": None, "description": None},
    {
        "name": "Cierva de Cerinea",
        "defeated_by": None,
        "captured_by": None,
        "description": None,
    },
    {
        "name": "Basilisco",
        "defeated_by": None,
        "captured_by": None,
        "description": None,
    },
    {
        "name": "Jabalí de Erimanto",
        "defeated_by": None,
        "captured_by": None,
        "description": None,
    },
]